//! The `claude` wrapper put first on `PATH` in Hive terminals, and the hooks settings it injects.

use std::fs::Permissions;
use std::io::{self, Write};
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::Path;

use serde_json::{Map, Value, json};

use crate::paths::Paths;

/// Claude Code events Hive observes; each one runs `hive hook <event>`.
pub const EVENTS: [&str; 12] = [
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "PostToolUseFailure",
    "PermissionRequest",
    "Notification",
    "Stop",
    "StopFailure",
    "SubagentStart",
    "SubagentStop",
    "SessionEnd",
];

/// Hook timeout in seconds. `hive hook` gives up after ~200 ms on its own; this only
/// bounds a stuck process, and stays within the 1.5 s budget Claude Code gives `SessionEnd`.
const HOOK_TIMEOUT_SECS: u64 = 1;

/// Writes the hooks settings and the `claude` wrapper, replacing earlier versions.
pub fn install(paths: &Paths, hive: &Path) -> io::Result<()> {
    let hive = hive
        .to_str()
        .ok_or_else(|| io::Error::other(format!("hive path is not UTF-8: {}", hive.display())))?;
    let bin = paths.bin_dir();
    std::fs::create_dir_all(&bin)?;
    let settings = paths.hooks_settings();
    write_atomic(&settings, format!("{:#}\n", hooks(hive)).as_bytes(), 0o644)?;
    write_atomic(&bin.join("claude"), &script(&bin, &settings), 0o755)
}

fn hooks(hive: &str) -> Value {
    let events: Map<String, Value> = EVENTS
        .iter()
        .map(|event| {
            let hook = json!({
                "type": "command",
                "command": hive,
                "args": ["hook", event],
                "timeout": HOOK_TIMEOUT_SECS,
            });
            (event.to_string(), json!([{ "hooks": [hook] }]))
        })
        .collect();
    json!({ "hooks": events })
}

fn script(bin: &Path, settings: &Path) -> Vec<u8> {
    let mut out = b"#!/bin/sh\n# Generated by hive; do not edit.\nhive_bin=".to_vec();
    out.extend(sh_quote(bin));
    out.extend(b"\nhive_settings=");
    out.extend(sh_quote(settings));
    out.extend(SCRIPT_BODY.as_bytes());
    out
}

/// Finds the first executable `claude` on `PATH` that is not this wrapper, then runs it.
/// Empty `PATH` entries (the current directory) are skipped on purpose.
const SCRIPT_BODY: &str = r#"
real=
old_ifs=$IFS
IFS=:
set -f
for dir in $PATH; do
    case $dir in "" | "$hive_bin") continue ;; esac
    if [ -f "$dir/claude" ] && [ -x "$dir/claude" ] && ! [ "$dir/claude" -ef "$0" ]; then
        real=$dir/claude
        break
    fi
done
set +f
IFS=$old_ifs
if [ -z "$real" ]; then
    echo "hive: no claude found in PATH" >&2
    exit 127
fi
if [ "${HIVE_WRAPPED-}" = 1 ]; then
    # A claude started from inside a hooked claude: its hooks are already in place.
    exec "$real" "$@"
fi
export HIVE_WRAPPED=1
exec "$real" --settings "$hive_settings" "$@"
"#;

/// Single-quotes `path` for `sh`.
fn sh_quote(path: &Path) -> Vec<u8> {
    let mut out = vec![b'\''];
    for &byte in path.as_os_str().as_bytes() {
        match byte {
            b'\'' => out.extend(b"'\\''"),
            _ => out.push(byte),
        }
    }
    out.push(b'\'');
    out
}

/// Replaces `path` in one step, so a terminal never runs a half-written file.
/// Writes `path` through a temporary file created with `mode` and renamed over it.
pub(crate) fn write_atomic(path: &Path, contents: &[u8], mode: u32) -> io::Result<()> {
    let tmp = path.with_extension("tmp");
    // A leftover could have looser permissions; a new file never shows the contents to others.
    let _ = std::fs::remove_file(&tmp);
    let mut file = std::fs::File::options()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(&tmp)?;
    file.write_all(contents)?;
    std::fs::set_permissions(&tmp, Permissions::from_mode(mode))?;
    std::fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::path::PathBuf;
    use std::process::{Command, Output};

    const FAKE_CLAUDE: &str = "#!/bin/sh\nprintf 'wrapped=%s\\n' \"${HIVE_WRAPPED-unset}\"\nfor a in \"$@\"; do printf '[%s]\\n' \"$a\"; done\n";

    struct Setup {
        tmp: tempfile::TempDir,
        paths: Paths,
    }

    impl Setup {
        /// Installs into a data dir whose name has a space and a single quote.
        fn new() -> Self {
            let tmp = tempfile::tempdir().unwrap();
            let paths = Paths {
                runtime: tmp.path().join("run"),
                data: tmp.path().join("it's data"),
            };
            install(&paths, Path::new("/opt/it's hive/hive")).unwrap();
            Self { tmp, paths }
        }

        fn wrapper(&self) -> PathBuf {
            self.paths.bin_dir().join("claude")
        }

        /// A directory holding an executable `claude` with the given script.
        fn claude_dir(&self, name: &str, script: &str) -> PathBuf {
            let dir = self.tmp.path().join(name);
            std::fs::create_dir_all(&dir).unwrap();
            let claude = dir.join("claude");
            std::fs::write(&claude, script).unwrap();
            std::fs::set_permissions(&claude, Permissions::from_mode(0o755)).unwrap();
            dir
        }

        fn fake(&self) -> PathBuf {
            self.claude_dir("real bin", FAKE_CLAUDE)
        }

        fn settings_arg(&self) -> String {
            format!(
                "[--settings]\n[{}]\n",
                self.paths.hooks_settings().display()
            )
        }
    }

    fn path_var(dirs: &[&Path]) -> std::ffi::OsString {
        std::env::join_paths(dirs).unwrap()
    }

    /// Runs `program` with only `PATH` (and `extra`) set; the real `claude` is never on it.
    /// Killed after 10 s (exit 124), so a wrapper that execs itself fails instead of hanging.
    fn run(program: &Path, path: &OsStr, extra: &[(&str, &str)], args: &[&str]) -> Output {
        Command::new("/usr/bin/timeout")
            .arg("10")
            .arg(program)
            .args(args)
            .env_clear()
            .env("PATH", path)
            .envs(extra.iter().copied())
            .output()
            .unwrap()
    }

    fn stdout(out: &Output) -> String {
        assert!(out.status.success(), "{out:?}");
        String::from_utf8(out.stdout.clone()).unwrap()
    }

    #[test]
    fn settings_are_added_and_args_pass_through() {
        let s = Setup::new();
        let path = path_var(&[&s.paths.bin_dir(), &s.fake()]);
        let out = run(&s.wrapper(), &path, &[], &["-p", "it's \"x\" y", ""]);
        let expected = format!("wrapped=1\n{}[-p]\n[it's \"x\" y]\n[]\n", s.settings_arg());
        assert_eq!(stdout(&out), expected);
    }

    #[test]
    fn already_wrapped_claude_gets_no_settings() {
        let s = Setup::new();
        let path = path_var(&[&s.paths.bin_dir(), &s.fake()]);
        let out = run(&s.wrapper(), &path, &[("HIVE_WRAPPED", "1")], &["a b"]);
        assert_eq!(stdout(&out), "wrapped=1\n[a b]\n");
    }

    #[test]
    fn hive_bin_dir_is_skipped_even_when_it_is_not_this_script() {
        let s = Setup::new();
        let bogus = s.claude_dir("bogus", "#!/bin/sh\necho bogus\n");
        // A copy of the wrapper that treats `bogus` as the hive bin dir.
        let copy = s.tmp.path().join("copy");
        std::fs::write(&copy, script(&bogus, Path::new("/s"))).unwrap();
        std::fs::set_permissions(&copy, Permissions::from_mode(0o755)).unwrap();
        let out = run(&copy, &path_var(&[&bogus, &s.fake()]), &[], &[]);
        assert_eq!(stdout(&out), "wrapped=1\n[--settings]\n[/s]\n");
    }

    #[test]
    fn wrapper_reached_through_a_symlinked_dir_is_skipped() {
        let s = Setup::new();
        let link = s.tmp.path().join("link");
        std::os::unix::fs::symlink(s.paths.bin_dir(), &link).unwrap();
        let path = path_var(&[&link, &s.fake()]);
        let expected = format!("wrapped=1\n{}", s.settings_arg());
        // Run as the symlinked path and as the real one: neither execs itself.
        assert_eq!(
            stdout(&run(&link.join("claude"), &path, &[], &[])),
            expected
        );
        assert_eq!(stdout(&run(&s.wrapper(), &path, &[], &[])), expected);
    }

    #[test]
    fn only_executable_regular_files_count() {
        let s = Setup::new();
        let not_exec = s.tmp.path().join("not exec");
        std::fs::create_dir(&not_exec).unwrap();
        std::fs::write(not_exec.join("claude"), "#!/bin/sh\necho no\n").unwrap();
        let a_dir = s.tmp.path().join("a dir");
        std::fs::create_dir_all(a_dir.join("claude")).unwrap();
        let path = std::ffi::OsString::from(format!(
            ":{}:{}:{}",
            not_exec.display(),
            a_dir.display(),
            s.fake().display()
        ));
        let out = run(&s.wrapper(), &path, &[], &[]);
        assert_eq!(stdout(&out), format!("wrapped=1\n{}", s.settings_arg()));
    }

    #[test]
    fn missing_claude_exits_127() {
        let s = Setup::new();
        let out = run(&s.wrapper(), &path_var(&[&s.paths.bin_dir()]), &[], &[]);
        assert_eq!(out.status.code(), Some(127));
        assert_eq!(out.stdout, b"");
        assert_eq!(out.stderr, b"hive: no claude found in PATH\n");
    }

    #[test]
    fn files_have_expected_modes() {
        let s = Setup::new();
        let mode = |p: &Path| std::fs::metadata(p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode(&s.wrapper()), 0o755);
        assert_eq!(mode(&s.paths.hooks_settings()), 0o644);
        let wrapper = std::fs::read_to_string(s.wrapper()).unwrap();
        assert!(wrapper.starts_with("#!/bin/sh\n# Generated by hive; do not edit.\n"));
    }

    #[test]
    fn hooks_settings_run_hive_hook_for_every_observed_event() {
        let s = Setup::new();
        let text = std::fs::read_to_string(s.paths.hooks_settings()).unwrap();
        let settings: Value = serde_json::from_str(&text).unwrap();
        let hooks = settings.as_object().unwrap()["hooks"].as_object().unwrap();
        assert_eq!(settings.as_object().unwrap().len(), 1);
        assert_eq!(hooks.len(), 12);
        for event in EVENTS {
            let expected = json!([{ "hooks": [{
                "type": "command",
                "command": "/opt/it's hive/hive",
                "args": ["hook", event],
                "timeout": 1,
            }]}]);
            assert_eq!(hooks[event], expected, "{event}");
        }
        assert!(!hooks.contains_key("WorktreeCreate"));
        assert!(!hooks.contains_key("WorktreeRemove"));
    }

    #[test]
    fn reinstall_overwrites_both_files() {
        let s = Setup::new();
        std::fs::write(s.wrapper(), "old").unwrap();
        std::fs::write(s.paths.hooks_settings(), "old").unwrap();
        install(&s.paths, Path::new("/new/hive")).unwrap();
        let settings = std::fs::read_to_string(s.paths.hooks_settings()).unwrap();
        assert!(settings.contains("\"/new/hive\""), "{settings}");
        assert!(
            std::fs::read_to_string(s.wrapper())
                .unwrap()
                .starts_with("#!/bin/sh")
        );
        let names: Vec<_> = std::fs::read_dir(s.paths.bin_dir()).unwrap().collect();
        assert_eq!(names.len(), 1, "temp files left behind");
    }

    #[test]
    fn non_utf8_hive_path_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            runtime: tmp.path().join("run"),
            data: tmp.path().join("data"),
        };
        let hive = Path::new(OsStr::from_bytes(b"/bad\xff/hive"));
        let err = install(&paths, hive).unwrap_err();
        assert!(err.to_string().contains("not UTF-8"), "{err}");
    }

    #[test]
    fn unwritable_data_dir_is_an_error() {
        let tmp = tempfile::tempdir().unwrap();
        let file = tmp.path().join("file");
        std::fs::write(&file, "").unwrap();
        let paths = Paths {
            runtime: tmp.path().join("run"),
            data: file,
        };
        assert!(install(&paths, Path::new("/hive")).is_err());
    }
}
