//! The `claude` wrapper put first on `PATH` in Hive terminals, and the hooks settings it injects.

use std::ffi::{OsStr, OsString};
use std::fs::Permissions;
use std::io::{self, Write};
use std::os::unix::ffi::{OsStrExt, OsStringExt};
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::Duration;

use tokio::io::AsyncReadExt;

use serde_json::{Map, Value, json};

use crate::paths::Paths;

/// Claude Code events Hive observes; each one runs `hive hook <event>`.
pub const EVENTS: [&str; 15] = [
    "SessionStart",
    "UserPromptSubmit",
    "PreToolUse",
    "PostToolUse",
    "PostToolUseFailure",
    "PermissionRequest",
    "Notification",
    "Stop",
    "StopFailure",
    "SubagentStart",
    "SubagentStop",
    "SessionEnd",
    "PreCompact",
    "PostCompact",
    "Elicitation",
];

/// Hook timeout in seconds. `hive hook` gives up after ~200 ms on its own; this only
/// bounds a stuck process, and stays within the 1.5 s budget Claude Code gives `SessionEnd`.
const HOOK_TIMEOUT_SECS: u64 = 1;

/// Worktree hooks (#15): event, `hive worktree` subcommand and timeout in seconds. Creating
/// runs `git worktree add` and copies the `.worktreeinclude` files; removing deletes the
/// worktree's files. Both then report to the service within ~200 ms.
const WORKTREE_HOOKS: [(&str, &str, u64); 2] = [
    ("WorktreeCreate", "hook-create", 60),
    ("WorktreeRemove", "hook-remove", 10),
];

/// Writes the hooks settings and the `claude` wrapper, replacing earlier versions.
pub fn install(paths: &Paths, hive: &Path) -> io::Result<()> {
    let hive = hive
        .to_str()
        .ok_or_else(|| io::Error::other(format!("hive path is not UTF-8: {}", hive.display())))?;
    let bin = paths.bin_dir();
    std::fs::create_dir_all(&bin)?;
    let settings = paths.hooks_settings();
    write_atomic(&settings, format!("{:#}\n", hooks(hive)).as_bytes(), 0o644)?;
    write_atomic(&bin.join("claude"), &script(&bin, &settings), 0o755)?;
    #[cfg(target_os = "macos")]
    crate::terminal::login::install(&bin)?;
    Ok(())
}

fn hooks(hive: &str) -> Value {
    let observed = EVENTS
        .iter()
        .map(|&event| (event, ["hook", event], HOOK_TIMEOUT_SECS));
    let worktree = WORKTREE_HOOKS
        .iter()
        .map(|&(event, command, timeout)| (event, ["worktree", command], timeout));
    let events: Map<String, Value> = observed
        .chain(worktree)
        .map(|(event, args, timeout)| {
            let hook = json!({
                "type": "command",
                "command": hive,
                "args": args,
                "timeout": timeout,
            });
            (event.to_owned(), json!([{ "hooks": [hook] }]))
        })
        .collect();
    json!({ "hooks": events })
}

fn script(bin: &Path, settings: &Path) -> Vec<u8> {
    let mut out = b"#!/bin/sh\n# Generated by hive; do not edit.\nhive_bin=".to_vec();
    out.extend(sh_quote(bin));
    out.extend(b"\nhive_settings=");
    out.extend(sh_quote(settings));
    out.extend(SCRIPT_BODY.as_bytes());
    out
}

/// Finds the first executable `claude` on `PATH` that is not this wrapper, then runs it.
/// Empty `PATH` entries (the current directory) are skipped on purpose.
const SCRIPT_BODY: &str = r#"
real=
old_ifs=$IFS
IFS=:
set -f
for dir in $PATH; do
    case $dir in "" | "$hive_bin") continue ;; esac
    if [ -f "$dir/claude" ] && [ -x "$dir/claude" ] && ! [ "$dir/claude" -ef "$0" ]; then
        real=$dir/claude
        break
    fi
done
set +f
IFS=$old_ifs
if [ -z "$real" ]; then
    echo "hive: no claude found in PATH" >&2
    exit 127
fi
if [ "${HIVE_WRAPPED-}" = 1 ]; then
    # A claude started from inside a hooked claude: its hooks are already in place.
    exec "$real" "$@"
fi
export HIVE_WRAPPED=1
exec "$real" --settings "$hive_settings" "$@"
"#;

/// The `claude` the wrapper in `bin` would run with `path` as `PATH`: the first executable
/// `claude` file outside `bin`, as the script looks for it (relative entries skipped too).
pub fn real_claude(path: Option<&OsStr>, bin: &Path) -> Option<PathBuf> {
    std::env::split_paths(path?)
        .filter(|dir| dir.is_absolute() && dir != bin)
        .map(|dir| dir.join("claude"))
        .find(|claude| {
            claude
                .metadata()
                .is_ok_and(|m| m.is_file() && m.permissions().mode() & 0o111 != 0)
        })
}

/// How long the user's shell gets to print its `PATH`.
pub const SHELL_TIMEOUT: Duration = Duration::from_secs(5);
/// The most the user's shell may print, its config's output included.
const SHELL_OUTPUT: u64 = 64 * 1024;
/// Run by the user's shell: prints its `PATH` on the last line (fish joins a quoted `PATH`
/// with `:` too). A fixed string: nothing from input goes into it.
const PRINT_PATH: &str = r#"printf '%s\n' "$PATH""#;

/// The user's shell as terminals start it (fish, after its config, on WSL), asked for its
/// `PATH`.
#[cfg(target_os = "linux")]
pub fn path_shell() -> (OsString, Vec<OsString>) {
    ("fish".into(), vec!["-c".into(), PRINT_PATH.into()])
}

/// The user's login shell (`$SHELL`), as terminals start it on macOS, asked for its `PATH`.
#[cfg(target_os = "macos")]
pub fn path_shell() -> (OsString, Vec<OsString>) {
    let var = std::env::var_os("SHELL");
    let shell = crate::terminal::login::launch(var, None, None, Path::new(""));
    let args = vec!["-l".into(), "-c".into(), PRINT_PATH.into()];
    (shell.program, args)
}

/// The `PATH` the user's terminals get, for chats and for finding the real `claude`: the
/// one `shell` (see [`path_shell`]) prints, else the service's `path` (started through
/// `wsl.exe`, it lacks what the user's config adds), then `~/.local/bin` and
/// `~/.claude/local`, where Claude Code installs itself. Empty entries are dropped.
pub async fn user_path(
    shell: (OsString, Vec<OsString>),
    path: Option<OsString>,
    home: Option<OsString>,
    timeout: Duration,
) -> OsString {
    let path = shell_path(&shell.0, &shell.1, timeout)
        .await
        .or(path)
        .unwrap_or_default();
    let installs = home
        .map(PathBuf::from)
        .into_iter()
        .flat_map(|home| [home.join(".local/bin"), home.join(".claude/local")]);
    let dirs = std::env::split_paths(&path)
        .filter(|dir| !dir.as_os_str().is_empty())
        .chain(installs);
    std::env::join_paths(dirs).unwrap_or(path)
}

/// The last line `program` prints with `args` (stdin and stderr closed), when it exits
/// successfully within `timeout` having printed at most [`SHELL_OUTPUT`] bytes.
async fn shell_path(program: &OsStr, args: &[OsString], timeout: Duration) -> Option<OsString> {
    let mut child = tokio::process::Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .kill_on_drop(true)
        .spawn()
        .ok()?;
    let stdout = child.stdout.take()?;
    let run = async {
        let mut out = Vec::new();
        let read = stdout.take(SHELL_OUTPUT + 1).read_to_end(&mut out).await;
        let status = child.wait().await.ok()?;
        (read.is_ok() && status.success() && out.len() as u64 <= SHELL_OUTPUT).then_some(out)
    };
    // ponytail: only the shell is killed on a timeout; a process it left behind lives on.
    let out = tokio::time::timeout(timeout, run).await.ok()??;
    let line = out
        .strip_suffix(b"\n")?
        .rsplit(|&byte| byte == b'\n')
        .next()?;
    (!line.is_empty()).then(|| OsString::from_vec(line.to_vec()))
}

/// Single-quotes `path` for `sh`.
fn sh_quote(path: &Path) -> Vec<u8> {
    let mut out = vec![b'\''];
    for &byte in path.as_os_str().as_bytes() {
        match byte {
            b'\'' => out.extend(b"'\\''"),
            _ => out.push(byte),
        }
    }
    out.push(b'\'');
    out
}

/// Replaces `path` in one step, so a terminal never runs a half-written file.
/// Writes `path` through a temporary file created with `mode` and renamed over it.
pub(crate) fn write_atomic(path: &Path, contents: &[u8], mode: u32) -> io::Result<()> {
    let tmp = path.with_extension("tmp");
    // A leftover could have looser permissions; a new file never shows the contents to others.
    let _ = std::fs::remove_file(&tmp);
    let mut file = std::fs::File::options()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(&tmp)?;
    file.write_all(contents)?;
    std::fs::set_permissions(&tmp, Permissions::from_mode(mode))?;
    std::fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::OsStr;
    use std::path::PathBuf;
    use std::process::{Command, Output, Stdio};

    /// [`user_path`] with `sh -c script` as the user's shell.
    async fn sh_path(script: &str, path: &str, home: Option<&str>, timeout: u64) -> OsString {
        let shell = ("sh".into(), vec!["-c".into(), script.into()]);
        let timeout = Duration::from_millis(timeout);
        user_path(shell, Some(path.into()), home.map(Into::into), timeout).await
    }

    #[tokio::test]
    async fn the_user_path_is_the_last_line_the_shell_prints_then_claudes_install_dirs() {
        let printed = sh_path("echo config says hi; echo /a:/b", "/s", Some("/h"), 5000).await;
        assert_eq!(printed, "/a:/b:/h/.local/bin:/h/.claude/local");
        // The shell's own `PATH`, printed as fish is asked for it.
        let (program, args) = path_shell();
        #[cfg(target_os = "linux")]
        assert_eq!((program, &args[..1]), ("fish".into(), &["-c".into()][..]));
        #[cfg(target_os = "macos")]
        {
            let shell = std::env::var_os("SHELL").filter(|shell| !shell.is_empty());
            let shell = shell.unwrap_or_else(|| "/bin/zsh".into());
            assert_eq!(
                (program, &args[..2]),
                (shell, &["-l".into(), "-c".into()][..])
            );
        }
        let service = std::env::var_os("PATH").unwrap();
        let sh = ("sh".into(), args[args.len() - 2..].to_vec());
        let printed = user_path(sh, None, None, SHELL_TIMEOUT).await;
        let expected: Vec<_> = std::env::split_paths(&service)
            .filter(|dir| !dir.as_os_str().is_empty())
            .collect();
        assert_eq!(printed, std::env::join_paths(expected).unwrap());
        // Exactly the most it may print.
        let full = "head -c 65535 /dev/zero | tr '\\0' a; echo";
        assert_eq!(sh_path(full, "/s", None, 5000).await, *"a".repeat(65535));
    }

    #[tokio::test]
    async fn without_the_shells_path_the_services_is_used() {
        for script in [
            "echo /a; exit 1",
            "printf /no-newline",
            "echo /a; echo",
            "head -c 65536 /dev/zero | tr '\\0' a; echo",
        ] {
            assert_eq!(
                sh_path(script, "/s::/t", None, 5000).await,
                "/s:/t",
                "{script}"
            );
        }
        assert_eq!(sh_path("exec sleep 5", "/s", None, 50).await, "/s");
        let missing = ("/nonexistent/sh".into(), vec![]);
        let home = Some("/h".into());
        let path = user_path(missing, None, home, SHELL_TIMEOUT).await;
        assert_eq!(path, "/h/.local/bin:/h/.claude/local");
        // A home that cannot go on a `PATH`.
        assert_eq!(sh_path("echo /a", "/s", Some("/h:x"), 5000).await, "/a");
    }

    const FAKE_CLAUDE: &str = "#!/bin/sh\nprintf 'wrapped=%s\\n' \"${HIVE_WRAPPED-unset}\"\nfor a in \"$@\"; do printf '[%s]\\n' \"$a\"; done\n";

    struct Setup {
        tmp: tempfile::TempDir,
        paths: Paths,
    }

    impl Setup {
        /// Installs into a data dir whose name has a space and a single quote.
        fn new() -> Self {
            let tmp = tempfile::tempdir().unwrap();
            let paths = Paths {
                runtime: tmp.path().join("run"),
                data: tmp.path().join("it's data"),
                config: tmp.path().join("config"),
            };
            install(&paths, Path::new("/opt/it's hive/hive")).unwrap();
            Self { tmp, paths }
        }

        fn wrapper(&self) -> PathBuf {
            self.paths.bin_dir().join("claude")
        }

        /// A directory holding an executable `claude` with the given script.
        fn claude_dir(&self, name: &str, script: &str) -> PathBuf {
            let dir = self.tmp.path().join(name);
            std::fs::create_dir_all(&dir).unwrap();
            let claude = dir.join("claude");
            std::fs::write(&claude, script).unwrap();
            std::fs::set_permissions(&claude, Permissions::from_mode(0o755)).unwrap();
            dir
        }

        fn fake(&self) -> PathBuf {
            self.claude_dir("real bin", FAKE_CLAUDE)
        }

        fn settings_arg(&self) -> String {
            format!(
                "[--settings]\n[{}]\n",
                self.paths.hooks_settings().display()
            )
        }
    }

    fn path_var(dirs: &[&Path]) -> std::ffi::OsString {
        std::env::join_paths(dirs).unwrap()
    }

    /// Runs `program` with only `PATH` (and `extra`) set; the real `claude` is never on it.
    /// Killed after 10 s, so a wrapper that execs itself fails instead of hanging.
    fn run(program: &Path, path: &OsStr, extra: &[(&str, &str)], args: &[&str]) -> Output {
        let mut child = Command::new(program)
            .args(args)
            .env_clear()
            .env("PATH", path)
            .envs(extra.iter().copied())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
        while child.try_wait().unwrap().is_none() && std::time::Instant::now() < deadline {
            std::thread::sleep(std::time::Duration::from_millis(10));
        }
        let _ = child.kill();
        child.wait_with_output().unwrap()
    }

    fn stdout(out: &Output) -> String {
        assert!(out.status.success(), "{out:?}");
        String::from_utf8(out.stdout.clone()).unwrap()
    }

    #[test]
    fn the_real_claude_is_the_first_executable_one_outside_the_bin_dir() {
        let s = Setup::new();
        let bin = s.paths.bin_dir();
        let fake = s.fake();
        // A folder named claude, and a claude that cannot run.
        let folder = s.tmp.path().join("folder");
        std::fs::create_dir_all(folder.join("claude")).unwrap();
        let plain = s.claude_dir("plain", "");
        std::fs::set_permissions(plain.join("claude"), Permissions::from_mode(0o644)).unwrap();
        let rel = Path::new("relative");
        let path = path_var(&[rel, &bin, &folder, &plain, &fake]);
        assert_eq!(real_claude(Some(&path), &bin), Some(fake.join("claude")));
        assert_eq!(real_claude(Some(&path_var(&[&bin, &plain])), &bin), None);
        assert_eq!(real_claude(None, &bin), None);
    }

    #[test]
    fn settings_are_added_and_args_pass_through() {
        let s = Setup::new();
        let path = path_var(&[&s.paths.bin_dir(), &s.fake()]);
        let out = run(&s.wrapper(), &path, &[], &["-p", "it's \"x\" y", ""]);
        let expected = format!("wrapped=1\n{}[-p]\n[it's \"x\" y]\n[]\n", s.settings_arg());
        assert_eq!(stdout(&out), expected);
    }

    #[test]
    fn already_wrapped_claude_gets_no_settings() {
        let s = Setup::new();
        let path = path_var(&[&s.paths.bin_dir(), &s.fake()]);
        let out = run(&s.wrapper(), &path, &[("HIVE_WRAPPED", "1")], &["a b"]);
        assert_eq!(stdout(&out), "wrapped=1\n[a b]\n");
    }

    #[test]
    fn hive_bin_dir_is_skipped_even_when_it_is_not_this_script() {
        let s = Setup::new();
        let bogus = s.claude_dir("bogus", "#!/bin/sh\necho bogus\n");
        // A copy of the wrapper that treats `bogus` as the hive bin dir.
        let copy = s.tmp.path().join("copy");
        std::fs::write(&copy, script(&bogus, Path::new("/s"))).unwrap();
        std::fs::set_permissions(&copy, Permissions::from_mode(0o755)).unwrap();
        let out = run(&copy, &path_var(&[&bogus, &s.fake()]), &[], &[]);
        assert_eq!(stdout(&out), "wrapped=1\n[--settings]\n[/s]\n");
    }

    #[test]
    fn wrapper_reached_through_a_symlinked_dir_is_skipped() {
        let s = Setup::new();
        let link = s.tmp.path().join("link");
        std::os::unix::fs::symlink(s.paths.bin_dir(), &link).unwrap();
        let path = path_var(&[&link, &s.fake()]);
        let expected = format!("wrapped=1\n{}", s.settings_arg());
        // Run as the symlinked path and as the real one: neither execs itself.
        assert_eq!(
            stdout(&run(&link.join("claude"), &path, &[], &[])),
            expected
        );
        assert_eq!(stdout(&run(&s.wrapper(), &path, &[], &[])), expected);
    }

    #[test]
    fn only_executable_regular_files_count() {
        let s = Setup::new();
        let not_exec = s.tmp.path().join("not exec");
        std::fs::create_dir(&not_exec).unwrap();
        std::fs::write(not_exec.join("claude"), "#!/bin/sh\necho no\n").unwrap();
        let a_dir = s.tmp.path().join("a dir");
        std::fs::create_dir_all(a_dir.join("claude")).unwrap();
        let path = std::ffi::OsString::from(format!(
            ":{}:{}:{}",
            not_exec.display(),
            a_dir.display(),
            s.fake().display()
        ));
        let out = run(&s.wrapper(), &path, &[], &[]);
        assert_eq!(stdout(&out), format!("wrapped=1\n{}", s.settings_arg()));
    }

    #[test]
    fn missing_claude_exits_127() {
        let s = Setup::new();
        let out = run(&s.wrapper(), &path_var(&[&s.paths.bin_dir()]), &[], &[]);
        assert_eq!(out.status.code(), Some(127));
        assert_eq!(out.stdout, b"");
        assert_eq!(out.stderr, b"hive: no claude found in PATH\n");
    }

    #[test]
    fn files_have_expected_modes() {
        let s = Setup::new();
        let mode = |p: &Path| std::fs::metadata(p).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode(&s.wrapper()), 0o755);
        assert_eq!(mode(&s.paths.hooks_settings()), 0o644);
        let wrapper = std::fs::read_to_string(s.wrapper()).unwrap();
        assert!(wrapper.starts_with("#!/bin/sh\n# Generated by hive; do not edit.\n"));
    }

    #[test]
    fn hooks_settings_run_hive_for_every_observed_event_and_worktree_hook() {
        let s = Setup::new();
        let text = std::fs::read_to_string(s.paths.hooks_settings()).unwrap();
        let settings: Value = serde_json::from_str(&text).unwrap();
        let hooks = settings.as_object().unwrap()["hooks"].as_object().unwrap();
        assert_eq!(settings.as_object().unwrap().len(), 1);
        assert_eq!(hooks.len(), 17);
        for event in EVENTS {
            let expected = json!([{ "hooks": [{
                "type": "command",
                "command": "/opt/it's hive/hive",
                "args": ["hook", event],
                "timeout": 1,
            }]}]);
            assert_eq!(hooks[event], expected, "{event}");
        }
        let worktree = |command: &str, timeout: u64| {
            json!([{ "hooks": [{
                "type": "command",
                "command": "/opt/it's hive/hive",
                "args": ["worktree", command],
                "timeout": timeout,
            }]}])
        };
        assert_eq!(hooks["WorktreeCreate"], worktree("hook-create", 60));
        assert_eq!(hooks["WorktreeRemove"], worktree("hook-remove", 10));
    }

    #[test]
    fn reinstall_overwrites_both_files() {
        let s = Setup::new();
        std::fs::write(s.wrapper(), "old").unwrap();
        std::fs::write(s.paths.hooks_settings(), "old").unwrap();
        install(&s.paths, Path::new("/new/hive")).unwrap();
        let settings = std::fs::read_to_string(s.paths.hooks_settings()).unwrap();
        assert!(settings.contains("\"/new/hive\""), "{settings}");
        assert!(
            std::fs::read_to_string(s.wrapper())
                .unwrap()
                .starts_with("#!/bin/sh")
        );
        let names: Vec<_> = std::fs::read_dir(s.paths.bin_dir()).unwrap().collect();
        assert_eq!(names.len(), 1, "temp files left behind");
    }

    #[test]
    fn non_utf8_hive_path_is_refused() {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths {
            runtime: tmp.path().join("run"),
            data: tmp.path().join("data"),
            config: tmp.path().join("config"),
        };
        let hive = Path::new(OsStr::from_bytes(b"/bad\xff/hive"));
        let err = install(&paths, hive).unwrap_err();
        assert!(err.to_string().contains("not UTF-8"), "{err}");
    }

    #[test]
    fn unwritable_data_dir_is_an_error() {
        let tmp = tempfile::tempdir().unwrap();
        let file = tmp.path().join("file");
        std::fs::write(&file, "").unwrap();
        let paths = Paths {
            runtime: tmp.path().join("run"),
            data: file,
            config: tmp.path().join("config"),
        };
        assert!(install(&paths, Path::new("/hive")).is_err());
    }
}
